- hosts: web
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: latest
  - name: Start Apache Service
    service:
      name: httpd
      state: started
  - name: Copy Index File to Apache Directory
    copy:
      src: /tmp/index.html
      dest: /var/www/html/
  - name: Restart Apache Service
    service:
      name: httpd
      state: restarted  